### PR TITLE
Proxy content fetching via server routes

### LINKED ISSUE #42: Cache content when exporting
I've noticed that `sapper export` exports static pages, but only caches content if it is requested from the same domain. So this template doesn't produce a truly static site (it still does lots of API requests).

The solution to this is the proxy the content fetch via server-routes (i.e. /api/[slug].js) as the original Sapper template does. This way all the API requests are cached and the site is finally static.

I'd be happy to attempt a PR for this, if it's something you would want to incorporate.

### PR DESCRIPTION
**Pull request by antony**
This will cause the exported site to be truly static.

Fixes https://github.com/sanity-io/sanity-template-sapper-blog/issues/42

I can't find a good way to test this, I've copied the code verbatim to my actual site and it works well, so hopefully there won't be any errors, but if you have a way to test the template first that would be great.

### CODE REVIEW

**Comment by antony** [comment]
any chance of getting this merged? It's getting stale

**Comment by eur2** [comment]
Yes please let's fix this issue! Sanity and Sapper are both super nice to use

**Comment by th-km** [comment]
Any update on this 👀

**Comment by PDoves** [comment]
I would like an update on this as well. 👀

**Comment by johngrasty** [comment]
This would be great to see merged, as it is much closer to what one would expect from a static site template. I tried the changes in the template as it stands currently and it works. I also upgraded a number of the packages to more recent versions, and though there may be a warning or two here and there, it works rather well, as it stands. (By the way, I tested with `svelte@3.29.7` and `rollup-plugin-svelte@^6.1.1`. (I believe `svelte@3.30` and `rollup-plugin-svelte@7.0.0.` would break it as there are some changes.)

**Comment by p10e** [comment]
Looks great - thank you so much for the PR Antony! And thanks everyone for your patience in waiting for us to merge this.

**Pull request merged**
